---
# Install registries certificates

- name: Create certificates folders
  become: yes
  file: 
    path: "/etc/docker/certs.d/{{lagoon_registry_cert.key}}"
    state: directory
    mode: 0755
  
- name: Install certificates
  become: yes
  get_url:
    url: "{{lagoon_registry_cert.value}}"
    dest: "/etc/docker/certs.d/{{lagoon_registry_cert.key}}"
    mode: 0400
