---
- name: "Ensure Docker registry {{ ek_registry.key }} is configured"
  include_tasks: "{{ ek_tasks_to_run }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/config-registry.yml"
  - "{{ ansible_distribution | lower }}/config-registry.yml"
  - "common/config-registry.yml"
  loop_control:
    loop_var: ek_tasks_to_run
