---
- name: Ensure Docker is registered as a system service
  include_tasks: "{{ ek_tasks_to_run }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/config-service.yml"
  - "{{ ansible_distribution | lower }}/config-service.yml"
  - "common/config-service.yml"
  loop_control:
    loop_var: ek_tasks_to_run
