---
- name: Ensure Docker daemon is configured
  include_tasks: "{{ ek_tasks_to_run }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/config-daemon.yml"
  - "{{ ansible_distribution | lower }}/config-daemon.yml"
  - "common/config-daemon.yml"
  loop_control:
    loop_var: ek_tasks_to_run
