---
- name: Configure Docker service
  include_tasks: config-service.yml

- name: Configure Docker TLS
  when: ek_docker_params.tls.enabled | default(true)
  include_tasks: config-tls.yml

- name: Configure Docker proxy
  when: ek_docker_proxy.http_proxy is defined and ek_docker_proxy.http_proxy != ""
  include_tasks: config-proxy.yml

- name: Configure user namespace
  when: ek_docker_params.remap | default(true)
  include_tasks: config-remap.yml

- name: Configure additional docker registries
  when: ek_docker_registries is defined
  include_tasks: config-registry.yml
  loop_control:
    loop_var: ek_registry
  loop: "{{ (ek_docker_registries | default({})) | dict2items }}"

- name: Configure Docker daemon
  when: ek_docker_params.daemon is defined
  include_tasks: config-daemon.yml

- name: Add Ansible user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
