---
# tasks file for ekara.docker
- name: Install docker/ansible configuration
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/docker-ansible.yml"
  - "{{ ansible_distribution | lower }}/docker-ansible.yml"
  loop_control:
    loop_var: ekara_machine_version

- name: Add docker group
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/docker-group.yml"
  - "{{ ansible_distribution | lower }}/docker-group.yml"
  loop_control:
    loop_var: ekara_machine_version

- name: Install docker
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/install.yml"
  - "{{ ansible_distribution | lower }}/install.yml"
  loop_control:
    loop_var: ekara_machine_version

- name: Add TLS for docker
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/config-tls.yml"
  - "{{ ansible_distribution | lower }}/config-tls.yml"
  loop_control:
    loop_var: ekara_machine_version
  when: ekara_docker_params.tls is defined

- name: Add Proxies for docker
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/proxies.yml"
  - "{{ ansible_distribution | lower }}/proxies.yml"
  loop_control:
    loop_var: ekara_machine_version
  when: ekara_docker_proxy.http_proxy is defined

- name: Add Usernamespace for docker
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/config-user-ns.yml"
  - "{{ ansible_distribution | lower }}/config-user-ns.yml"
  loop_control:
    loop_var: ekara_machine_version
  when: ekara_docker_params['userns-remap'] is defined

- name: Add private registry for docker
  include_tasks: registries.yml
  tags: ansible
  loop_control:
    loop_var: ekara_registry
  loop: "{{ekara_docker_all.registries|dict2items}}"
  when: ekara_docker_all.registries is defined

- name: Update configuration
  include_tasks: update-json.yml
  vars:
    docker_daemon_new_config: "{{ekara_docker_params}}"

- name: Start docker
  include_tasks: "{{ekara_machine_version}}"
  tags: ansible
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/daemon-start.yml"
  - "{{ ansible_distribution | lower }}/daemon-start.yml"
  loop_control:
    loop_var: ekara_machine_version
