---
- name: Ensure PIP packages are installed
  include_tasks: "{{ ek_tasks_to_run }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/pip.yml"
  - "{{ ansible_distribution | lower }}/pip.yml"
  - "common/pip.yml"
  loop_control:
    loop_var: ek_tasks_to_run
