---
# Install registries certificates

- name: Create certificates folders
  become: yes
  file: 
    path: "/etc/docker/certs.d/{{lagoon_registry.key}}"
    state: directory
    mode: 0755
  
- name: Install certificates
  become: yes
  get_url:
    url: "{{lagoon_registry.value.certificate}}"
    dest: "/etc/docker/certs.d/{{lagoon_registry.key}}"
    mode: 0400

- name: Log into private registry
  docker_login:
    registry: "{{lagoon_registry.key}}"
    username: "{{lagoon_registry.value.username}}"
    password: "{{lagoon_registry.value.password}}"
