---
- name: Ensure operating system is up-to-date
  include_tasks: "{{ ek_tasks_to_run }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/system.yml"
  - "{{ ansible_distribution | lower }}/system.yml"
  - "common/system.yml"
  loop_control:
    loop_var: ek_tasks_to_run
