##### Update configuration
---
- set_fact:
    docker_daemon_update: "{{docker_daemon_new_config | mandatory}}"

- name: Create docker directories
  become: true
  file: path="{{item}}" state=directory mode=0755
  with_items:
  - /etc/docker

- set_fact:
    docker_labels: "{{ (docker_labels|default([])) + [item.key+'='+item.value] }}"
  loop: "{{ekara_labels | dict2items}}"

- name: Add labels
  set_fact:
    docker_daemon_update: "{{ docker_daemon_update | combine({'labels': docker_labels}) }}"
  when:
  - docker_labels is defined

- name: Copy daemon.json to remote directory
  become: true
  copy:
    content: "{{docker_daemon_update | to_nice_json }}"
    dest: /etc/docker/daemon.json
