---
- name: Create systemd docker directory
  become: true
  file: path="{{item}}" state=directory mode=0755
  with_items:
  - /etc/systemd/system/docker.service.d

- name: Install systemd custom configuration
  become: true
  copy:
    src: files/systemd/docker.conf
    dest: /etc/systemd/system/docker.service.d
