---
- name: Get Docker's official GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
- name: Add stable repository
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    state: present
- name: Install docker
  become: true
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
  - docker-ce
