---
- name: "Ensure certificate folder for registry {{ ek_registry.key }} exists"
  become: true
  file:
    path: "/etc/docker/certs.d/{{ ekara_registry.key }}"
    state: directory
    mode: 0755

- name: "Install certificate for registry {{ ek_registry.key }}"
  become: true
  get_url:
    url: "{{ ek_registry.value.cert }}"
    dest: "/etc/docker/certs.d/{{ ek_registry.key }}"
    mode: 0400

- name: "Log into {{ ek_registry.key }} private registry"
  when: ek_registry.value.username is defined
  docker_login:
    registry: "{{ ek_registry.key }}"
    username: "{{ ek_registry.value.username }}"
    password: "{{ ek_registry.value.password }}"
